# Data Acquisition
- Winnipeg Housing Permit Inspection
- https://data.Winnipeg.ca

In [47]:
import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. 
# Note no username or password:
client = Socrata("data.winnipeg.ca", "dOrQbTCqCNLTutDyoQLwoGjNE")


# Getting data
wpg_inspect_defects = client.get("ytpf-7jye")

# Convert to pandas DataFrame
wpg_inspect_defects_df = pd.DataFrame.from_records(wpg_inspect_defects)

In [48]:
wpg_inspect_defects_df.head()

,year,inspection_type,ward,permit_count,inspection_count,defect_count,location
0,2023,Residential Electrical,Point Douglas,612,1269,387,"POLYGON ((627305.320657589 5534130.15426131,62..."
1,2018,Residential Building,Point Douglas,96,795,504,"POLYGON ((627305.320657589 5534130.15426131,62..."
2,2015,Residential Plumbing,City of Winnipeg,1,3,0,"POLYGON ((620532.479605648 5530298.54839773,62..."
3,2023,Residential Electrical,River Heights - Fort Garry,1103,2785,1308,"POLYGON ((629727.197330781 5526669.96746367,62..."
4,2018,Residential Plumbing,Transcona,275,1479,268,"POLYGON ((641758.9588 5532766.734,641758.6455 ..."

In [49]:
wpg_inspect_defects_df.tail()

,year,inspection_type,ward,permit_count,inspection_count,defect_count,location
520,2024,Residential Plumbing,Waverley West,624.0,2463.0,437.0,"POLYGON ((630638.094848997 5521018.33267953,62..."
521,2024,Residential Building,Fort Rouge - East Fort Garry,270.0,1238.0,795.0,"POLYGON ((634256.632830763 5528647.13968144,63..."
522,2024,Residential Electrical,Elmwood - East Kildonan,600.0,1470.0,586.0,"POLYGON ((636079.093845205 5532301.9782023,635..."
523,2024,Residential Building,Old Kildonan,546.0,4050.0,2713.0,"POLYGON ((626990.2463798 5534110.92768153,6273..."
524,2024,Residential Building,Transcona,757.0,4258.0,3168.0,"POLYGON ((640201.124428291 5532538.32352198,64..."

In [50]:
wpg_inspect_defects_df.columns

Index(['year', 'inspection_type', 'ward', 'permit_count', 'inspection_count',
       'defect_count', 'location'],
      dtype='object')

In [51]:
wpg_inspect_defects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525 entries, 0 to 524
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              525 non-null    object
 1   inspection_type   525 non-null    object
 2   ward              525 non-null    object
 3   permit_count      525 non-null    object
 4   inspection_count  525 non-null    object
 5   defect_count      525 non-null    object
 6   location          525 non-null    object
dtypes: object(7)
memory usage: 28.8+ KB

In [52]:
wpg_inspect_defects_df['inspection_count'] = pd.to_numeric(wpg_inspect_defects_df['inspection_count'],errors = 'coerce')
wpg_inspect_defects_df['permit_count'] = pd.to_numeric(wpg_inspect_defects_df['permit_count'],errors = 'coerce')
wpg_inspect_defects_df['defect_count'] = pd.to_numeric(wpg_inspect_defects_df['defect_count'],errors = 'coerce')
wpg_inspect_defects_df['year'] = pd.to_numeric(wpg_inspect_defects_df['year'],errors = 'coerce')

In [53]:
wpg_inspect_defects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525 entries, 0 to 524
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              525 non-null    int64
 1   inspection_type   525 non-null    object
 2   ward              525 non-null    object
 3   permit_count      525 non-null    float64
 4   inspection_count  525 non-null    float64
 5   defect_count      525 non-null    float64
 6   location          525 non-null    object
dtypes: float64(3), int64(1), object(3)
memory usage: 28.8+ KB

In [54]:
wpg_inspect_defects_df['inspection_type'].unique()

array(['Residential Electrical', 'Residential Building',
       'Residential Plumbing'], dtype=object)

In [55]:
wpg_inspect_defects_df['year'].unique()

array([2023, 2018, 2015, 2017, 2019, 2016, 2022, 2021, 2020, 2024])

In [56]:
wpg_inspect_defects_df['ward'].unique()

array(['Point Douglas', 'City of Winnipeg', 'River Heights - Fort Garry',
       'Transcona', 'Elmwood - East Kildonan', 'Old Kildonan',
       'St. Vital', 'South Winnipeg - St. Norbert', 'Mynarski',
       'Charleswood - Tuxedo - Whyte Ridge', 'Daniel McIntyre',
       'North Kildonan', 'St. Boniface', 'Fort Rouge - East Fort Garry',
       'Waverley West', 'St. Norbert - Seine River',
       'St. James - Brooklands - Weston', 'St. Charles',
       'Charleswood - Tuxedo - Westwood', 'St. James'], dtype=object)

In [ ]:
#wpg_inspect_defects_df_drop = wpg_inspect_defects_df.drop('location', axis=1, inplace=False)

wpg_inspect_defects_df.drop('location', axis=1, inplace=True)
wpg_inspect_defects_df.head()

In [ ]:
wpg_inspect_defects_df.shape

In [ ]:
wpg_inspect_defects_df_pv = pd.pivot_table(wpg_inspect_defects_df, values=['inspection_count','defect_count'],
                        index=['ward','year'], columns=['inspection_type'])
wpg_inspect_defects_df_pv

In [ ]:
wpg_inspect_defects_df_pv.shape

In [ ]:
wpg_inspect_defects_df_pv.columns.map('_'.join)

In [ ]:
wpg_inspect_defects_df_pv.columns = wpg_inspect_defects_df_pv.columns.map('_'.join)
wpg_inspect_defects_df_pv

In [ ]:
wpg_inspect_defects_df_pv = wpg_inspect_defects_df_pv.reset_index()
wpg_inspect_defects_df_pv

In [ ]:
wpg_inspect_defects_df_pv['total_inspection_count'] = wpg_inspect_defects_df_pv['inspection_count_Residential Building'] + wpg_inspect_defects_df_pv['inspection_count_Residential Electrical'] + wpg_inspect_defects_df_pv['inspection_count_Residential Plumbing']
wpg_inspect_defects_df_pv['total_defect_count'] = wpg_inspect_defects_df_pv['defect_count_Residential Building'] + wpg_inspect_defects_df_pv['defect_count_Residential Electrical'] + wpg_inspect_defects_df_pv['defect_count_Residential Plumbing']
wpg_inspect_defects_df_pv['total_defect_ratio'] = wpg_inspect_defects_df_pv['total_defect_count']/wpg_inspect_defects_df_pv['total_inspection_count']
wpg_inspect_defects_df_pv

In [ ]:
wpg_inspect_defects_target = wpg_inspect_defects_df_pv[['ward','year','total_defect_ratio']]
wpg_inspect_defects_target

In [ ]:
wpg_inspect_defects_target.info()

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(16, 8))
sns.set_theme(style="whitegrid")

# Plot the responses for different events and regions
sns.lineplot(x="year", y="total_defect_ratio",
             hue="ward", 
             data=wpg_inspect_defects_target, 
             palette=sns.color_palette("deep", 20),
            linewidth=2.5)
plt.show()

In [ ]:
#Census 2006 - Dwelling
wpg_census_2006_dwelling = client.get("cem6-ktqa")

# Convert to pandas DataFrame
wpg_census_2006_dwelling_df = pd.DataFrame.from_records(wpg_census_2006_dwelling)

In [ ]:
wpg_census_2006_dwelling_df.head()

In [ ]:
wpg_census_2006_dwelling_df.tail()

In [ ]:
wpg_census_2006_dwelling_df.columns

In [ ]:
wpg_census_2006_dwelling_df.info()

In [ ]:
wpg_census_2006_dwelling_df['dwelling_cost_owner_average_value_dwelling'] = pd.to_numeric(wpg_census_2006_dwelling_df['dwelling_cost_owner_average_value_dwelling'],errors = 'coerce')
wpg_census_2006_dwelling_df['dwelling_occupied_average_rooms'] = pd.to_numeric(wpg_census_2006_dwelling_df['dwelling_occupied_average_rooms'],errors = 'coerce')
wpg_census_2006_dwelling_df['dwelling_condition_regular_maintenance'] = pd.to_numeric(wpg_census_2006_dwelling_df['dwelling_condition_regular_maintenance'],errors = 'coerce')
wpg_census_2006_dwelling_df['dwelling_condition_major_repairs'] = pd.to_numeric(wpg_census_2006_dwelling_df['dwelling_condition_major_repairs'],errors = 'coerce')

In [ ]:
wpg_census_2006_dwelling_df.info()

In [ ]:
wpg_census_2006_dwelling_df_sel = wpg_census_2006_dwelling_df[['boundary_type','boundary_name','dwelling_cost_owner_average_value_dwelling','dwelling_occupied_average_rooms','dwelling_condition_regular_maintenance','dwelling_condition_major_repairs']]
wpg_census_2006_dwelling_df_sel

In [ ]:
wpg_census_2006_dwelling_df_sel = wpg_census_2006_dwelling_df_sel.loc[wpg_census_2006_dwelling_df_sel['boundary_type'] == 'Ward']

In [ ]:
wpg_census_2006_dwelling_df_sel['boundary_name'].unique()

In [ ]:
ax = sns.barplot(y="boundary_name", x="dwelling_cost_owner_average_value_dwelling", facecolor="blue", data=wpg_census_2006_dwelling_df_sel)

In [ ]:
ax = sns.barplot(y="boundary_name", x="dwelling_occupied_average_rooms", facecolor="green", data=wpg_census_2006_dwelling_df_sel)

In [ ]:
ax = sns.barplot(y="boundary_name", x="dwelling_condition_regular_maintenance", facecolor="grey", data=wpg_census_2006_dwelling_df_sel)

In [ ]:
ax = sns.barplot(y="boundary_name", x="dwelling_condition_major_repairs", facecolor="orange", data=wpg_census_2006_dwelling_df_sel)

In [ ]:
# Census - Households
wpg_census_households = client.get("nmk5-uwfw")

# Convert to pandas DataFrame
wpg_census_households_df = pd.DataFrame.from_records(wpg_census_households)

In [ ]:
wpg_census_households_df.head()

In [ ]:
wpg_census_households_df.columns

In [ ]:
wpg_census_households_df_sel = wpg_census_households_df.loc[wpg_census_households_df['boundary_type'] == 'Ward']
wpg_census_households_df_sel

In [ ]:
wpg_census_households_df_sel = wpg_census_households_df_sel[['census_year','boundary_name','income_average','size_average_person']]
wpg_census_households_df_sel

In [ ]:
wpg_census_households_df_sel['income_average'] = pd.to_numeric(wpg_census_households_df_sel['income_average'],errors = 'coerce')
wpg_census_households_df_sel['size_average_person'] = pd.to_numeric(wpg_census_households_df_sel['size_average_person'],errors = 'coerce')
ax = sns.barplot(y="boundary_name", x="size_average_person", hue="census_year", data=wpg_census_households_df_sel)

In [ ]:
ax = sns.barplot(y="boundary_name", x="income_average", hue="census_year", data=wpg_census_households_df_sel)

In [ ]:
#Census - Labour Force Activities
wpg_census_labour_act = client.get("pcyz-4rbx")

# Convert to pandas DataFrame
wpg_census_labour_act_df = pd.DataFrame.from_records(wpg_census_labour_act)
wpg_census_labour_act_df.head()

In [ ]:
wpg_census_labour_act_df["boundary_type"].unique()

In [ ]:
print(wpg_census_labour_act_df.columns)

In [ ]:
wpg_census_labour_act_df.head()